### PR TITLE
TP2000-1124: Add validation for quota definition volume

### PR DESCRIPTION
**Pull request by eadpearce**
# TP2000-1124: Add validation for quota definition volume

Screenshot 2023-11-15 at 12 29 51

### CODE REVIEW

**Review by CPrich905 — APPROVED** [review]
LGTM, one non-blocking nit-picky question: if there is an intention to add more validation tests, would this one be better named something like `test_quota_definition_validation_for_higher_than_initial_volume`?

**Comment by eadpearce** [comment]
@CPrich905 Yeah I think if we did add more validation we could modify that test or parametrize it

**Comment by eadpearce** [comment]
@CPrich905 ...that is to say. I'll update it to test more of the validation because I probably should have done that anyway

**Review by CPrich905 — APPROVED** [review]
Nice one! Also like calling the single function twice rather than duplicating it :)

**Pull request merged**
