### PR TITLE
Regenerate all migrations

### PR DESCRIPTION
**Pull request by andyhd**
Running migrations in the staging deployment fails with `InconsistentMigrationHistory`.

This change deletes all migrations and replaces them with newly generated ones.

⚠️  This will require you to drop and recreate your local database.

### CODE REVIEW

**Review by NDevox — COMMENTED** [review]
Can we not use https://docs.djangoproject.com/en/3.1/topics/migrations/#migration-squashing ?

**Comment by andyhd** [comment]
sorry, i'll try that

**Comment by andyhd** [comment]
no, that fails on `common` unfortunately

**Comment by NDevox** [comment]
Yeah I expected that as we have some custom migration scripts in there. Worth a try though.

We could get rid of the custom stuff and it would probably start working, but given we're early on this may be the easiest approach (otherwise we have to wait for everyones databases to become consistent). On the other hand doing this will require _every DB_ to be dropped and recreated as you state.

If we're happy with this fine. I do ask for this not to be merged until I make a seed DB dump which works with the changes though (shouldn't take long).

**Comment by andyhd** [comment]
Sure, I will hold off. Unfortunately, I don't know if this will fix the deployment until it is merged.

**Comment by NDevox** [comment]
Done.

If you want to fix the DB without having to drop and rebuild you can run the following:

```sql
TRUNCATE public.django_migrations;

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2021-01-07 11:11:29.462591+00
2	auth	0001_initial	2021-01-07 11:11:29.50935+00
3	workbaskets	0001_initial	2021-01-07 11:11:29.542805+00
4	contenttypes	0002_remove_content_type_name	2021-01-07 11:11:29.563798+00
5	common	0001_initial	2021-01-07 11:11:29.627388+00
6	footnotes	0001_initial	2021-01-07 11:11:29.687037+00
7	additional_codes	0001_initial	2021-01-07 11:11:29.771839+00
8	admin	0001_initial	2021-01-07 11:11:29.808225+00
9	admin	0002_logentry_remove_auto_add	2021-01-07 11:11:29.820423+00
10	admin	0003_logentry_add_action_flag_choices	2021-01-07 11:11:29.831073+00
11	auth	0002_alter_permission_name_max_length	2021-01-07 11:11:29.84906+00
12	auth	0003_alter_user_email_max_length	2021-01-07 11:11:29.857923+00
13	auth	0004_alter_user_username_opts	2021-01-07 11:11:29.870529+00
14	auth	0005_alter_user_last_login_null	2021-01-07 11:11:29.87933+00
15	auth	0006_require_contenttypes_0002	2021-01-07 11:11:29.88074+00
16	auth	0007_alter_validators_add_error_messages	2021-01-07 11:11:29.891319+00
17	auth	0008_alter_user_username_max_length	2021-01-07 11:11:29.904618+00
18	auth	0009_alter_user_last_name_max_length	2021-01-07 11:11:29.914593+00
19	auth	0010_alter_group_name_max_length	2021-01-07 11:11:29.938102+00
20	auth	0011_update_proxy_permissions	2021-01-07 11:11:29.956336+00
21	auth	0012_alter_user_first_name_max_length	2021-01-07 11:11:29.966873+00
22	certificates	0001_initial	2021-01-07 11:11:30.056909+00
23	commodities	0001_initial	2021-01-07 11:11:30.278361+00
24	taric	0001_initial	2021-01-07 11:11:30.351132+00
25	exporter	0001_initial	2021-01-07 11:11:30.381727+00
26	geo_areas	0001_initial	2021-01-07 11:11:30.527809+00
27	importer	0001_initial	2021-01-07 11:11:30.560421+00
28	regulations	0001_initial	2021-01-07 11:11:30.977312+00
29	measures	0001_initial	2021-01-07 11:11:31.854689+00
30	quotas	0001_initial	2021-01-07 11:11:32.725687+00
31	measures	0002_auto_20210106_1533	2021-01-07 11:11:33.002235+00
32	sessions	0001_initial	2021-01-07 11:11:33.011243+00
\.
```

**Review by NDevox — APPROVED** [review]

**Comment by andyhd** [comment]
Requesting review from everyone as a heads-up!

**Pull request merged**
